### ISSUE TITLE
Issue in !promote

### ISSUE THREAD

**Issue by SpEcHiDe** [PaulSonOfLars/tgbot#34]
Why is [this](https://github.com/PaulSonOfLars/tgbot/blob/master/tg_bot/modules/admin.py#L51) line kept commented?

**Comment by PaulSonOfLars** [comment]
Undocumented issues in the telegram api mean that in some cases, assigning that permission throws an exception. I haven't been able to pinpoint where or why that's the case, and given that it isn't a particularly important permission to have, I decided to opt for stability > completeness, and removed it. 
This may or may not be fixed in the current bot api, but as said, seemingly random exceptions make it v hard to test.
