### ISSUE TITLE
Bug it can turn down a bot even though u are not admin 

### ISSUE THREAD

**Issue by YurieCo** [PaulSonOfLars/tgbot#49]
I think this is the most important bug ever can be found
if u add the @BanhammerMarie_bot to the group fulls of bots then type start it causes the @BanhammerMarie_bot to be freeze tested 
@1maverick1

**Comment by PaulSonOfLars** [comment]
Can I have steps to reproduce? I'm not sure I understand what you've done. Add me to the chat if necessary.

**Comment by PaulSonOfLars** [comment]
Discussed on telegram, in the support chat.

This bug report is irrelevant, consists of 
"If I DDOS this service, this service stops. This is a security flaw." there is also no proof of actual DDOS as the user failed to recreate the issue; suggesting another user was the root of the attack.

Sidenote: the python design of marie makes it hard to add proper rate limiting, mainly due to the GIL. I recommend using rose to avoid downtime.
